### PR TITLE
Respect docs_dir from referenced mkdocs.yml

### LINKED ISSUE #40: Add support for docs_dir mkdocs.yml config
## Feature Suggestion
`mkdocs-monorepo-plugin` should understand and support the `docs_dir` config in included `mkdocs.yml` files.

## Context

By supporting `docs_dir` in referenced `mkdocs.yml` files, we open up a couple of nice use-cases:

- The possibility to reference a sibling `mkdocs.yml` configuration which contains subsets of documentation from submodules within a monorepo (while the submodules themselves have their own, complete `mkdocs.yml` files).
- The possibility for simpler submodule topologies with simpler documentation needs (e.g. submodules which only need a single `README.md`, which is more conveniently kept at the submodule's root directory, rather than in a `docs` sub-folder)

Naturally, other use-cases would be possible as well.

## Original Report
Hi i was wondering if it would be possible to allow for the use of docs_dir attribute in a mkdocs.yml config file

My issue is that we have a submodule that is used in many projects, and it has a lot of documentation. These many projects don't all need the full documentation from the submodule, but only a subset.  
There for the idea was to create a mkdocs_submodule.yml in the root git repository that only includes the needed documentation.

This would allow us to build tailored documentation packages for each of our projects.

### PR DESCRIPTION
**Pull request by haneul**
Fixes #40

### CODE REVIEW

**Review by iamEAP — COMMENTED** [review]
😮 &nbsp;this is great @haneul!  And the added test is very much appreciated as well.

I was attempting to use your branch with a set up using @neobonde's use-case where there are sibling `mkdocs.yml` files at the top-level, but one of whose `docs_dir` config points at a nested sub-directory, e.g.

```
├── docs
│   └── index.md
├── mkdocs.yml
├── submodule_mkdocs.yml   <--- Subset of documentation in submodule/docs, in this example only. submodule/docs/reference.md
├──  submodule
│   ├── docs 
│   │   └── index.md
│   │   └── reference.md
│   └── mkdocs.yml  <--- Full and normal documentation of submodule, independent of main repo.
```

But I was unable to get it to work.  What do you think's going on, there?

**Comment by haneul** [comment]
oh. let me check the scenario and update here.

**Comment by haneul** [comment]
@iamEAP fixed the issue. (also added a test case covering it)

**Review by iamEAP — APPROVED** [review]
Fantastic!  Thanks again for your contribution @haneul.  Should be available with version `0.4.14`.

**Pull request merged**
